### ISSUE TITLE
Doubt about multispectrum

### ISSUE THREAD

**Issue by librauee** [PlumedSerpent/FcaNet#5]
According to your paper, it seems that you split the channels first, then from each feature map of channels you choose one DCT coefficient then concat them and feed to FC layer,  so  different order of  fidx_u and  fidx_v will lead to different result, am I right?

**Comment by PlumedSerpent** [comment]
I‘m not the author of this paper. I think your claim is correct that different orders of fidx_u and fidx_v  will lead to different DCT weights, which means the channels may be multiplied by another weights if we change the order. I'm not sure about my understanding, but I think the following FC layer may adaptively adjust the weights because it's fully connected. You can ask the author in (zhihu)[https://zhuanlan.zhihu.com/p/338904015].

**Comment by librauee** [comment]
Thanks for your responding😀
